name: Deploy Angular Portfolio to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js (v22 LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Dependências
        run: npm ci

      - name: Build do Projeto Angular
        run: npx ng build --base-href=/

      # Essa etapa inspeciona e remove o README da pasta compilada caso o Angular tenha copiado
      - name: Remover README acidental da pasta de build
        run: |
          rm -f ./dist/meu-portfolio/browser/README.md
          rm -f ./dist/meu-portfolio/README.md
          ls -la ./dist/meu-portfolio/browser || ls -la ./dist/meu-portfolio

      - name: Upload dos arquivos buildados
        uses: actions/upload-pages-artifact@v3
        with:
          # É AQUI QUE ESTAVA O SEGREDO! O path obrigatório do Angular moderno é na subpasta browser:
          path: ./dist/meu-portfolio/browser

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4